export default [ { "name": "start",
"title": "Building a web app with ES6", 
"short": "Start",
} ,{ "name": "intro",
"title": "Introduction", 
"short": "Intro",
} ,{ "name": "tips",
"title": "Some tips before we start", 
"short": "Tips",
} ,{ "name": "install-node",
"title": "Installing Node.js and NPM", 
"short": "Install (Node.js and NPM)",
} ,{ "name": "install-jspm",
"title": "Installing jspm", 
"short": "Install (jspm)",
} ,{ "name": "install-grunt",
"title": "Installing Grunt", 
"short": "Install (Grunt)",
} ,{ "name": "install-git",
"title": "Installing Git", 
"short": "Install (Git)",
} ,{ "name": "clone-repo",
"title": "Cloning the skeleton repository", 
"short": "Git clone",
} ,{ "name": "setup-index",
"title": "Setting up index.html", 
"short": "Setup (index.html)",
} ,{ "name": "setup-angular",
"title": "Setting up Angular", 
"short": "Setup (Angular)",
} ,{ "name": "setup-router",
"title": "Setting up the router", 
"short": "Setup (Router)",
} ,{ "name": "navigation-planning",
"title": "Planning the navigation component", 
"short": "Navigation (planning)",
} ,{ "name": "navigation-factory",
"title": "Creating slides with a factory", 
"short": "Navigation (factory)",
} ,{ "name": "navigation-service",
"title": "Handling slides with a service", 
"short": "Navigation (service)",
} ,{ "name": "navigation-react",
"title": "Using React with the navigation directive", 
"short": "Navigation (component)",
} ,{ "name": "navigation-directive",
"title": "Creating the navigation directive", 
"short": "Navigation (directive)",
} ,{ "name": "index-planning",
"title": "Planning the index component", 
"short": "Index (planning)",
} ,{ "name": "index-active",
"title": "Extending the slides with active functionality", 
"short": "Index (active)",
} ,{ "name": "index-react",
"title": "Creating the React components for the index directive", 
"short": "Index (components)",
} ,{ "name": "index-directive",
"title": "Creating the index directive", 
"short": "Index (directive)",
} ,{ "name": "server-setup",
"title": "Setting up dependencies for the socket server", 
"short": "Server (setup)",
} ,{ "name": "server-sockets",
"title": "A Protocol for messages to use with our sockets", 
"short": "Server (sockets)",
} ,{ "name": "progress-service",
"title": "Setting up services for the progress directive", 
"short": "Progress (services)",
} ,{ "name": "progress-react",
"title": "Setting up React components for the progress directive", 
"short": "Progress (component)",
} ,{ "name": "progress-directive",
"title": "Setting up the progress directive", 
"short": "Progress (directive)",
} ,{ "name": "help-service",
"title": "Setting up services for help queue", 
"short": "Help queue (service)",
} ,{ "name": "help-react",
"title": "Setting up React components for help queue directive", 
"short": "Help queue (component)",
} ,{ "name": "help-directive",
"title": "Setting up the help queue directive", 
"short": "Help queue (directive)",
} ,{ "name": "conclusion",
"title": "Conclusion", 
"short": "Conclusion",
} ,{ "name": "bonus-slides",
"title": "Bonus - Generating slides", 
"short": "Bonus (slides)",
} ,{ "name": "bonus-css",
"title": "Bonus - Generating the CSS", 
"short": "Bonus (CSS)",
} ,{ "name": "bonus-keypress",
"title": "Bonus - Adding keypress-events", 
"short": "Bonus (keypress)",
} ,{ "name": "bonus-touch",
"title": "Bonus - Adding touch-events", 
"short": "Bonus (touch)",
} ,{ "name": "bonus-server",
"title": "Bonus - How the server works", 
"short": "Bonus (server)",
} ,{ "name": "bonus-heroku",
"title": "Bonus - Uploading the application to Heroku", 
"short": "Bonus (Heroku)",
} ,{ "name": "bonus-resources",
"title": "Bonus - Some nifty resources", 
"short": "Bonus (resources)",
} ,{ "name": "final-words",
"title": "Some final words", 
"short": "Final words",
} ];